config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'

  # get 'reports/list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'application#index'
  controller :version do
    get 'version' => :version
  end

  controller :application do
    post 'slack_to_user/:user_name' => :slack_to_user
    post 'slack_to_channel/:channel_name' => :slack_to_channel
  end

  # resources :reports

  controller :reports do
    get '/reports', to: 'reports#index', as: 'reports'
    # get 'reports' => :index
    get 'reports/:project', to: 'reports#show', as: 'report'
    get 'reports/:project/:date/:type/:service', to: 'reports#show_report', as: 'show_report'

    get 'report_notified/:project/:date/:service', to: 'reports#notify', as: 'send_notification'
    put 'reports/update', to: 'reports#update', as: 'update_reports'

  end

  controller :travis do
    get 'docker_image_check/:service_name/:image_to_check', to: 'travis#check_docker_image', as: 'check_docker_image'
    put 'dynamic_tags/:project/:cuc_tag', to: 'travis#set_dynamic_tags', as: 'set_dynamic_tags'
    put 'dynamic_tags_deploy', to: 'travis#dynamic_tags_deploy', as: 'dynamic_tags_deploy'
    get 'dynamic_tags/:project/:cuc_tag', to: 'travis#get_dynamic_tags', as: 'get_dynamic_tags'
    get 'dynamic_tags_history/:project/:cuc_tag', to: 'travis#get_dynamic_tags_history', as: 'get_dynamic_tags_history'
    get 'dynamic_trigger_tags/:project', to: 'travis#get_dynamic_trigger_tags', as: 'get_dynamic_trigger_tags'
  end

  controller :seed_data_service do
    get 'seed_story_categories/:project' => :list_all_categories
    get 'seed_story_ids/:project' => :list_all_stories
    get 'seed_story_ids/:project/:category' => :list_category_stories
    get 'seed_story/:story_id' => :show_story
    post 'seed_story/:project/:category/:story_id' => :create_story
  end

  controller :ui_mock_service do
    get 'ui_mock/analytic/:type' => :show_analytic
    get 'ui_mock/search/:type' => :show_search
    get 'ui_mock/aggregate/:type/:id' => :show_aggregate
    get 'ui_mock/query/:type' => :show_query
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ReportsHelper
  # respond_to :html, :json
  def index
    @projects = ApplicationHelper.projects

  end

  def show
    @project = {}
    project = params[:project]
    reports = ReportsHelper.get_all_reports(project)
    out = {}
    reports.each do |report|
      date = report['date']
      tag = report['tag']
      level = report['report_level']

      out[date] ||= {}
      out[date][tag] ||= {}
      if out[date][tag][level].nil? || out[date][tag][level]['update_time'] < report['update_time']
        out[date][tag][level] = report
      end
    end
    sorted_out_keys = out.keys.sort {|a, b| Date.strptime(b, "%m-%d-%y") <=> Date.strptime(a, "%m-%d-%y")}
    sorted_out_keys.each do |k|
      @project[k] = out [k]
    end
    @project
  end

  def show_report
    file_name = "#{params[:date]}/#{params[:service]}@#{params[:type]}.html"
    file = ReportsHelper.get_report_content(params[:project], file_name)
    file.sub!('PEDMatch Cucumber Reports', "#{params[:service].upcase} BDD Reports (#{params[:type]}, #{params[:date]})")
    render :html => file.html_safe
  end

  def update
    payload = JSON.parse(request.body.read)
    ReportsHelper.update(payload)
    render json: {message: "#{payload['project']} report for #{payload['date']} is updated!"}
  end

  def notify
    response = ReportsHelper.notify_user(params[:project], params[:date], params[:service], request.base_url)
    if response.include?('ERROR:')
      render status: 400, json: {message: response}
    else
      render status: 200, json: {message: response}
    end
  end

  # def authorize
  #   if session['logged_in'] == 'yes'
  #     puts 'skipping authorize'
  #   else
  #     session['logged_in'] = 'yes'
  #     puts 'First time authorize'
  #   end
  # end
end

app/helpers/reports_helper.rb
require 'aws-sdk'
require 'tempfile'
require 'json'
require 'active_support/core_ext/date/calculations'

module ReportsHelper
  REPORT_TABLE = 'test_management_cucumber_report'

  def self.bucket(project)
    ApplicationHelper.report_params(project)['bucket']
  end


  def self.get_all_reports(project)
    cut_time = (Date.tomorrow - ApplicationHelper.report_params(project)['days_to_keep']).to_time.to_i
    criteria = {project: {comparison_operator: 'EQ', attribute_value_list: [project]}}
    criteria['update_time'] = {comparison_operator: 'GE', attribute_value_list: [cut_time]}
    ApplicationHelper.dynamodb_get_items(REPORT_TABLE, criteria)
  end

  def self.get_all_file_paths(project)
    criteria = {project: {comparison_operator: 'EQ', attribute_value_list: [project]}}
    ApplicationHelper.dynamodb_distinct_column(REPORT_TABLE, 'report_file', criteria)
  end

  def self.get_report_detail(project, report_name)
    criteria = {project: {comparison_operator: 'EQ', attribute_value_list: [project]}}
    criteria['report_file'] = {comparison_operator: 'EQ', attribute_value_list: [report_name]}
    result = ApplicationHelper.dynamodb_get_items(REPORT_TABLE, criteria)
    if result.size == 1
      result[0]
    else
      {}
    end
  end

  def self.get_report_content(project, report_name)
    dir = "#{File.dirname(__FILE__)}/../../test-reports/#{report_name}"
    puts "dir for report folder"+ dir
    File.read(dir)
    # ApplicationHelper.s3_file_read(bucket(project), report_name)
  end

  def self.keep_report?(project, date)
    return true if date==''
    date_obj = Date.strptime(date, '%m-%d-%y')
    Date.today - date_obj <= ApplicationHelper.report_params(project)['days_to_keep']
  end

  def self.update(params)
    project = params['project']
    date = params['date']
    repo = params['trigger_repo'].present? ? params['trigger_repo'] : 'N/A'
    commit = params['trigger_commit'].present? ? params['trigger_commit'] : 'N/A'
    bkt = bucket(project)
    ApplicationHelper.s3_file_list(bkt, date, 'html').each do |file|
      slash_parts = file.split('/')
      next unless slash_parts.size == 2
      at_parts = slash_parts[1].split('@')
      next unless at_parts.size == 2
      tag = at_parts[1].gsub('.html', '')
      next unless tag == params['tag']
      level = at_parts[0]
      time = ApplicationHelper.s3_file_modify_time(bkt, file).to_i
      file_content = ApplicationHelper.s3_file_read(bkt, file)
      passed = file_content.split('Passed: ')[1].split('<')[0]
      failed = file_content.split('Failed: ')[1].split('<')[0]
      record = {
          project: project,
          date: date,
          tag: tag,
          trigger_author: params['trigger_author'].strip, #the author value might have ending whitespace
          trigger_repo: repo,
          trigger_commit: commit,
          travis_url: params['travis_url'],
          passed: passed,
          failed: failed,
          update_time: time,
          s3_bucket: bkt,
          report_file: file,
          report_level: level,
          latest: 'true'
      }
      previous = get_latest_report(project, date, tag, level)
      unless previous.empty?
        previous[0]['latest']='false'
        ApplicationHelper.dynamodb_put_item(REPORT_TABLE, previous[0])
      end
      ApplicationHelper.dynamodb_put_item(REPORT_TABLE, record)
    end
  end

  def self.get_latest_report(project, date, service, level='all')
    filter = {project: {comparison_operator: 'EQ', attribute_value_list: [project]}}
    filter['date'] = {comparison_operator: 'EQ', attribute_value_list: [date]}
    filter['tag'] = {comparison_operator: 'EQ', attribute_value_list: [service]}
    filter['latest'] = {comparison_operator: 'EQ', attribute_value_list: ['true']}
    filter['report_level'] = {comparison_operator: 'EQ', attribute_value_list: [level]} unless level == 'all'
    ApplicationHelper.dynamodb_get_items(REPORT_TABLE, filter)
  end

  def self.notify_user(project, date, service, report_link)
    record = get_latest_report(project, date, service)
    return "There is no report for #{project}/#{date}/#{service}!" if record.size < 1
    author = record[0]['trigger_author']
    unless author.present?
      return "Report #{project}/#{date}/#{service} doesn't contain trigger_author information!"
    end
    message = "\nPlease check: <#{record[0]['travis_url']}|Travis Log>"
    place_holder = 'xxLEVELxx'
    bdd_report_link = "#{report_link}/reports/#{project}/#{date}/#{service}/#{place_holder}"
    bdd_report_link = "<#{bdd_report_link}|Test Report (#{place_holder})>"
    record.each do |r|
      link = bdd_report_link.gsub(place_holder, r['report_level'])
      message += "\n #{r['report_level']} Test: #{r['passed']} Passed | #{r['failed']} Failed. #{link}"
    end
    message += "\nTrigger Repo: #{record[0]['trigger_repo']} (#{record[0]['trigger_commit']})"
    criticals = record.select {|r| r['report_level']!='non-critical'}
    failed = criticals[0]['failed'].to_i
    #need to consider both critical and rerun, take the less failed value
    criticals.each {|c| failed = c['failed'].to_i if c['failed'].to_i < failed}
    theme = failed > 0 ? 'danger' : 'good'
    time = Time.at(record[0]['update_time']).strftime("%Y-%m-%d %H:%M:%S")
    title = failed > 0 ? "#{project} #{service} BDD Test Failed @#{time} :sob:" : "#{project} #{service} BDD Test Passed @#{time} :tada:"
    msg = SlackSender.new.send_message(theme, title, message, author)
    msg
  end

  def self.zero_if_nil(val)
    val.nil? ? '0' : val
  end

  def self.getStats(report_type)
    retVal = Hash.new()
    retVal.default = 0
    if report_type
      retVal = {
          passed: ReportsHelper.zero_if_nil(report_type['passed']),
          failed: ReportsHelper.zero_if_nil(report_type['failed'])
      }
    end
    retVal
  end

  def self.build_travis_details(details)
    # Here I am getting all the (critical or non-critical or rerun) hash that has a travis_url
    available = details.select {|_run, data| !(data['travis_url'].nil?)}
    # Here I am taking travis url in the first hash
    url = available[available.keys.first]['travis_url']
    {
        text: url.split('/').last,
        url: url
    }
  end
end

app/views/reports/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Test Reporter</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.1.5/angular.min.js"></script>

  <style type="text/css">
    @charset "UTF-8";

    .service-stats-passed {
      color: green;
      font-weight: bold;
    }

    .service-stats-failed {
      color: red;
      font-weight: bold;
    }
  </style>

</head>

<body bgcolor="#67BCDB" ng-app>

<div class="container">
  <div class="page-header">
    <h1>Test Projects</h1>
  </div>
  <p class="lead">Projects being tracked </p>
  <div>
    <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.upcase, report_url(project) %></li>
    <% end %>
    </ul>
  </div>
</div>

<!--<div class="container">-->
  <!--<%= yield %>-->
<!--</div>-->

<%#<footer class="footer">
    <div class="container">
      <p class="text-muted">Place sticky footer content here.</p>
    </div>
  </footer>%>


</body>

app/views/reports/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Test Reporter</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.1.5/angular.min.js"></script>

  <style type="text/css">
    @charset "UTF-8";

    .service-stats-passed {
      color: green;
      font-weight: bold;
    }

    .service-stats-failed {
      color: red;
      font-weight: bold;
    }



    table {
      border: 2px solid steelblue;
      table-layout: fixed;
    }
    th, td {
      padding: 1px;
      border: 1px solid steelblue;
    }
    th {
      text-align: center;
    }

    .passed {color: green;}
    .failed {color: red;}
    .info {color: #487dce;}
    .lively {
      color: steelblue;
      background-color: #e2e2e2;
      border: solid darkslateblue 1px;
      font-size: large;
    }
    .fixit {
      position: fixed;
      top: 2%;
      right: 10%;
    }

</style>

</head>

<body bgcolor="#67BCDB" ng-app>

<div class="container">
  <div class="page-header">
    <h1>Test Reports</h1>
  </div>
  <p class="lead">List of last 10 days test reports generated by Cucumber. For older reports please check S3 folder.</p>
</div>
<div class="fixit">
  <%= link_to reports_path do %>
    <span ><%= image_tag 'Home.png', width: 50, height: 50, alt:"Home"%><p align="center">Home</p></span>
  <% end %>
</div>

<div class="container">
  <div>
    <table style="width:100%">
      <thead>
      <tr>
        <th style="width: 20%">Tag</th>
        <th style="width: 20%">Critical</th>
        <th style="width: 20%">Rerun</th>
        <th style="width: 20%">Non-Critical</th>
        <th style="width: 20%">Travis Run</th>
      </tr>
      </thead>
      <tbody>
      <% @project.each do |run_date, data| %>
        <table style="width:100%" >
          <thead>
          <tr>
            <th colspan="5" bgcolor="#e6f2ff" style="padding: 1px; width: 100%"><%= run_date %></th>
          </tr>
          </thead>
          <tbody>
          <% data.each do |tag, details| %>
              <% critical = ReportsHelper.getStats(details['critical']) %>
              <% rerun = ReportsHelper.getStats(details['rerun']) %>
              <% non_critical = ReportsHelper.getStats(details['non-critical']) %>
              <% travis_url = ReportsHelper.build_travis_details(details) %>
            <tr>
              <td style="width: 20%"><strong><%= tag.split('_').map(&:capitalize).join(' ')%></strong></td>
              <td style="width: 20%">
                <%= link_to show_report_url(date: run_date, service: 'critical', type: tag), target: :_blank do%>
                  <span class="passed"><%= critical[:passed]%></span> / <span class="failed"><%=  critical[:failed] %></span>
                <% end %>
              </td>
              <td style="width: 20%">
                <%= link_to show_report_url(date: run_date, service: 'rerun', type: tag), target: :_blank do%>
                    <span class="passed"><%= rerun[:passed]%></span> / <span class="failed"><%=  rerun[:failed] %></span>
                <% end %>
              </td>
              <td style="width: 20%">
                <%= link_to show_report_url(date: run_date, service: 'non-critical', type: tag), target: :_blank do%>
                    <span class="passed"><%= non_critical[:passed]%></span> / <span class="failed"><%=  non_critical[:failed] %></span>
                <% end %>
              </td>
              <td style="width: 20%; word-wrap: break-word">
                <%= link_to travis_url[:url], target: :_blank do%>
                  <span class="info"> <%= travis_url[:text]  %></span>
                <% end %>
              </td>
            </tr>

          <% end %>
          </tbody>
        </table>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%#<footer class="footer">
    <div class="container">
      <p class="text-muted">Place sticky footer content here.</p>
    </div>
  </footer>%>

</body>
</html>